{% set name = "nncf" %}
{% set version = "2.17.0" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94de6a0860e8e09f76171068de3d4f54b91908a5bd1d0ef8dbe86aaed875e9c1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --install-option=--release

requirements:
  host:
    - pip ==22.2
    - python {{ python_min }}
    - python-build
    - setuptools >=61.0
    - wheel
  run:
    - jsonschema >=3.2.0
    - natsort >=7.1.0
    - networkx >=2.6,<=3.5.0
    - ninja >=1.10.0.post2,<1.12
    - numpy >=1.24.0,<2.3.0
    - openvino-telemetry >=2023.2.0
    - packaging >=20.0
    - pandas >=1.1.5,<2.3
    - psutil
    - pydot >=1.4.1,<=3.0.4
    - pymoo >=0.6.0.1
    - rich >=13.5.2
    - safetensors >=0.4.1
    - scikit-learn >=0.24.0
    - scipy >=1.3.2
    - tabulate >=0.9.0
    - python >={{ python_min }}

test:
  imports:
    - nncf
    - nncf.api
#  commands:
#    - pip check  # won't work because conda's version of ninja does not get registered in pip - https://github.com/mesonbuild/meson-python/issues/60, https://github.com/pypa/pip/issues/11157
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/openvinotoolkit/nncf
  summary: Neural Networks Compression Framework
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
    - vshampor
    - nikita-malininn
    - alexsu52
